groups:
- name: Scrape Targets
  rules:
  - alert: Persistent Instance Down
    expr: up{persistent="true"} == 0
    for: 15s
    annotations:
      title: '{{ $labels.instance }} is down'
      description: 'Job `{{ $labels.job }}` has down instance: `{{ $labels.instance }}`'
    labels:
      severity: 'critical'
      down_time_trigger: '15 seconds'
      type: 'infrastructure'

  - alert: Server-Core jobs down
    expr: up{instance=~"Server-Core.*"} == 0
    for: 15s
    annotations:
      title: '{{ $labels.job }} is down'
      description: 'Job `{{ $labels.job }}` has down instance: `{{ $labels.instance }}`'
    labels:
      severity: 'critical'
      down_time_trigger: '15 seconds'
      type: 'infrastructure'

  - alert: Core VMs down
    expr: up{instance=~"apps.*|Apps.*|services.*|Services.*"} == 0 
    for: 15s
    annotations:
      title: '{{ $labels.job }} is down'
      description: 'Job `{{ $labels.job }}` has down instance: `{{ $labels.instance }}`'
    labels:
      severity: 'critical'
      down_time_trigger: '15 seconds'
      type: 'infrastructure'