global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - AlertManager_Infrastructure:9093

rule_files:
    - "alert_scrape_targets.yml"
    - "alert_internet_connection.yml"
    - "alert_resource_consumption.yml"
    - "alert_temperatures.yml"

scrape_configs:

  - job_name: "Server_Load"
    static_configs:
      - targets: [
          "Ryzen9.Horna.local:4445",
          "Server-Core.Horna.local:4445"
        ]

  - job_name: "SpeedTest"
    static_configs:
      - targets: [
          "Apps.Horna.local:8000"
        ]
  
  - job_name: "Docker_Containers"
    static_configs:
      - targets: [
          "services.Horna.local:54569", 
          "apps.Horna.local:54569", 
          "dockerserver.Horna.local:54569", 
          "codespace.Horna.local:54569"
        ]
  
  - job_name: "Omada"
    static_configs:
      - targets: [
          "Apps.Horna.local:51772"
        ]

  - job_name: "GreenCell"
    static_configs:
      - targets: [
          "apps.Horna.local:58969"
        ]