# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - AlertManager_Infrastructure:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert_scrape_targets.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: "Server_Load"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [
          "Ryzen9.Horna.local:4445",
          "Server-Core.Horna.local:4445"
        ]

  - job_name: "SpeedTest"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [
          "Apps.Horna.local:8000"
        ]
        labels:
          persistent: "true"
  
  - job_name: "Docker_Containers"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [
          "services.Horna.local:54569", 
          "apps.Horna.local:54569", 
          "dockerserver.Horna.local:54569", 
          "codespace.Horna.local:54569"
        ]
  
  - job_name: "Omada"
    static_configs:
      - targets: [
          "Apps.Horna.local:51772",
          "codespace.Horna.local:51772"
        ]
        labels:
          persistent: "true"