global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'
  group_wait: 15s
  group_interval: 15s

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prometheus_alerts'
    api_url_file: /etc/alertmanager/slack_webhook_url.config
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      
      *Description:* {{ .Annotations.description }}

      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}